<?php
$this->headLink()->appendStylesheet($this->baseUrl() . '/modules/default/css/form.css');
$title = new Snep_Title("Status");
echo $title->getHtml();
echo Snep_Bar::get($this->translate("status links"),  NULL, NULL, "reports");

echo $this->form;
?>
<div class="description_form"><p><h2>Status dos Links</h2>

<p>
Esta rotina do sistema mostra exclusivamente informações sobre o Status de Links de Placas.
Se nenhuma placa for identificada pelo Sistema, uma mensagem de AVISO será exibida.
</p>

<p>
Uma Lista das Placas instaladas no sistema é exibida para que sejam exibidas informações das placas
selecionadas. Existem basicamente 4 modelos de placas:
</p>
<ul>
    <li>E1</li>
    <li>FXS</li>
    <li>FXO</li>
    <li>GSM</li>    
</ul>

<p>
O Sistema identifica as placas apenas pela sua "posição no Sistema", precedido sempre da letra <strong>B</strong>.
</p>

<strong>As informações exibidas são:</strong>
<ul>
    <li><strong>1.</strong> Identificação da Placa</li>
    <li><strong>2.</strong> Status do(s) Link(s) da Placa – quando disponível. </li>
    <li><strong>3.</strong> Resumo dos Status dos Canais da Placa</li>
    <li><strong>4.</strong> Informações sobre cada Canal da Placa</li>
    <ul>
        <li>Nome/Número do Canal (Ex: C00)</li>
        <li>Status do Canal, fornecido pelo Asterisk</li>
        <li>Status da Chamada do Canal, fornecido pelo hardware da Placa</li>
        <li>Status do Canal, fornecido pelo hardware da Placa</li>
    </ul>
</ul>
  </p></div>

<?php
    $buttons = new Snep_Buttons();
    $buttons->addOption('gerar', 'snep_form', true);
    $buttons->addOption('cancel', $this->baseUrl().'/index.php/');
    echo $buttons->getHtml();
?>
