<?php
$this->headLink()->appendStylesheet( $this->baseUrl() . "/modules/default/css/index.css" );
$this->headScript()->prependFile( $this->baseUrl() . '/includes/javascript/scriptaculous/lib/prototype.js');
$this->headScript()->prependFile( $this->baseUrl() . '/includes/javascript/removeItem.js');

$this->headLink()->appendStylesheet($this->baseUrl() . '/modules/default/css/form.css');
$title = new Snep_Title("Entries");
$title->addOption('import', $this->baseUrl()."/index.php/default/".Zend_Controller_Front::getInstance()->getRequest()->getControllerName() . '/import');
$title->addOption('export', $this->baseUrl()."/index.php/default/".Zend_Controller_Front::getInstance()->getRequest()->getControllerName() . '/export');
echo $title->getHtml();
echo $this->render('filter.phtml');
?>
<table>
   <thead>
      <tr>
         <th class="numeric"> <?php echo Snep_Order::getLink($this, 'Code', 'codigo') ?> </th>
         <th> <?php echo Snep_Order::getLink($this, $this->translate('Name'), 'nome') ?> </th>
         <th> <?php echo Snep_Order::getLink($this, $this->translate('Startup Time'), 'tpm') ?> </th>
         <th> <?php echo Snep_Order::getLink($this, $this->translate('Fragmentation Time'), 'tdm') ?> </th>
         <th> <?php echo Snep_Order::getLink($this, $this->translate('Tariff to Fixed'), 'tbf') ?> </th>
         <th> <?php echo Snep_Order::getLink($this, $this->translate('Tariff to Cellular'), 'tbc') ?> </th>
         <th colspan="2" class="action"> <?php echo $this->translate('Actions') ?> </th>
      </tr>
   </thead>
   <tbody>
    <?php
    $c = 0;
    if($this->carrier):
        foreach($this->carrier as $carrier ): ?>
            <?php ($c ? $c = 0 : $c = 1 ); ?>
            <tr class="c<?php echo $c ?>">
                <td> 
                    <b> <?php echo $carrier['codigo'] ?> </b>
                </td>
                <td>
                    <b> <?php echo $carrier['nome'] ?> </b>
                </td>
                <td>
                    <b> <?php echo $carrier['tpm'] ?> </b>
                </td>
                <td> 
                    <?php echo $carrier['tdm'] ?>
                </td>
                <td>
                    <?php if($carrier['tbf']) echo new Zend_Currency(array('value' => $carrier['tbf'] )) ?>
                </td>
                <td> 
                   <?php if($carrier['tbc']) echo new Zend_Currency(array('value' => $carrier['tbc'] )) ?>
                </td>
                <td class="action">
                    <a class="alterar" href="<?php echo $this->url ?>/edit/id/<?php echo $carrier['codigo'] ?>"></a>
                </td>
                <td class="action">
                    <?php $this->remove_msg = $this->translate("Do you wish to remove this record?");?>
                    <span class="excluir" onclick="remove_item('<?php echo $this->url ?>','<?php echo $carrier['codigo'] ?>','<?php echo $this->remove_msg ?>')"></span>
                </td>
            </tr>
        <?php endforeach ?>
    <?php endif ?>
</table>

<?php echo $this->render('pagination.phtml') ?>
