<?php
$this->headLink()->appendStylesheet( $this->baseUrl() . "/modules/default/css/index.css" );

$title = new Snep_Title("Entries");
$title->addOption('import', $this->baseUrl()."/index.php/default/".Zend_Controller_Front::getInstance()->getRequest()->getControllerName() . '/import');
$title->addOption('export', $this->baseUrl()."/index.php/default/".Zend_Controller_Front::getInstance()->getRequest()->getControllerName() . '/export');
echo $title->getHtml();

echo $this->render('filter.phtml')
?>

<table>
   <thead>
      <tr>
         <th class="action"> 
            <?php echo Snep_Order::getLink($this, 'Code', 'id') ?>
         </th>
         <th> 
            <?php echo Snep_Order::getLink($this, 'Name', 'name') ?>
         </th>
         <th> <?php echo $this->translate('Contacts numbers') ?></th>
         <th class="action" colspan="2"> 
            <?php echo $this->translate('Actions') ?>
         </th>
      </tr>
   </thead>
   <tbody>
    <?php
    $c = 0;
    if($this->contactgroups):
        foreach( $this->contactgroups as $group ): ?>
            <?php ($c ? $c = 0 : $c = 1 ); ?>
      
            <tr class="c<?php echo $c ?>">
                <td class="numeric">
                    <b> <?php echo $group['id'] ?> </b>
                </td>
                <td> 
                    <?php echo $group['name'] ?>
                </td>
                <td>  <?php echo count(Snep_ContactGroups_Manager::getGroupContacts($group['id']));  ?> </td>
                <td class="action">
                    <a class="alterar" href="<?php echo $this->url ?>/edit/id/<?php echo $group['id'] ?>"></a>
                </td>
                <td class="action">
                    <a class="excluir" href="<?php echo $this->url ?>/remove/id/<?php echo $group['id'] ?>"></a>
                </td>
            </tr>
        <?php endforeach ?>
    <?php endif ?>
</table>

<?php echo $this->render('pagination.phtml') ?>