<?php
$this->headLink()->appendStylesheet( $this->baseUrl() . "/modules/default/css/form.css" );

$title = new Snep_Title("Entries");
echo $title->getHtml();
echo Snep_Bar::get($this->translate("Migration of Group Members"),  $this->translate("Contact Group"), $this->baseUrl()."/index.php/default/contact-groups");


echo $this->form;

?>
<div class="description_form"><p>Essa função realiza a migração dos contatos associados ao grupo para um novo grupo ou efetua a exclusão dos contatos associados.</p></div>
<?php 
$buttons = new Snep_Buttons();
$buttons->addOption('save', 'snep_form', true);
$buttons->addOption('cancel', $this->baseUrl().'/index.php/contact-groups/');
echo $buttons->getHtml();
?>
<script type="text/javascript">
	$(".snep_form").prepend("<div class='error_box'><?php echo $this->message ?></div>");

	$('#option-migrate').change(function(){
		if($(this).attr('checked')) $("#group").removeAttr("disabled");
		else $("#group").attr('disabled', true);
    });
    $('#option-remove').change(function(){
		if($(this).attr('checked')) $("#group").attr('disabled', true);
		else $("#group").removeAttr("disabled");
    });
    
  
</script>




