<?php
$title = new Snep_Title("Entries");
$title->addOption('import', $this->baseUrl()."/index.php/default/".Zend_Controller_Front::getInstance()->getRequest()->getControllerName() . '/import');
$title->addOption('export', $this->baseUrl()."/index.php/default/".Zend_Controller_Front::getInstance()->getRequest()->getControllerName() . '/export');
echo $title->getHtml();

$this->headLink()->appendStylesheet( $this->baseUrl() . "/modules/default/css/index.css" );
$this->headScript()->prependFile( $this->baseUrl() . '/includes/javascript/scriptaculous/lib/prototype.js');
$this->headScript()->prependFile( $this->baseUrl() . '/includes/javascript/removeItem.js');
echo $this->render('filter.phtml')
?>

<table cellspacing="0" cellpadding="0" border="0" align="center" width="100%" >
   <thead>
      <tr>
         <th> <?php echo Snep_Order::getLink($this, 'Code', 'codigo') ?> </th>
         <th> <?php echo Snep_Order::getLink($this, 'Name', 'nome') ?> </th>
         <th> <?php echo Snep_Order::getLink($this, 'Type', 'tipo') ?> </th>
         <th> <?php echo Snep_Order::getLink($this, 'Description', 'descricao') ?> </th>
         <th colspan="2" class="action"> <?php echo $this->translate('Actions') ?> </th>
      </tr>
   </thead>
   <tbody>
    <?php
    $c = 0;
    if( $this->costcenter ) :
        foreach($this->costcenter as $id => $costcenter ): ?>
            <?php ($c ? $c = 0 : $c = 1 ); ?>
            <tr class="c<?php echo $c ?>">
                <td> <b> <?php echo $costcenter['codigo'] ?> </b> </td>
                <td> <?php echo $costcenter['nome'] ?> </td>
                <td> <?php echo $this->types[$costcenter['tipo']] ?> </td>
                <td> <?php echo $costcenter['descricao'] ?> </td>
                <td class="action">
                    <a class="alterar" href="<?php echo $this->url ?>/edit/id/<?php echo $costcenter['codigo'] ?>"> </a>
                </td>
                <td class="action">
                   <a class="excluir" href="<?php echo $this->url ."/remove/id/".  $costcenter['codigo'] ?>"></a>
                </td>
            </tr>
        <?php endforeach ?>
    <?php endif?>
</table>

<?php echo $this->render('pagination.phtml') ?>