<style type="text/css">
.regra0{
	width: 30px;
	height: 30px;
	display: block;
	margin: 0px;
	background-image: url(<?php echo $this->baseUrl() ?>/modules/default/img/off_button.png);
}
.regra1{
	width: 30px;
	height: 30px;
	display: block;
	margin: 0px;
	background-image: url(<?php echo $this->baseUrl() ?>/modules/default/img/active_button.png);
}
</style>
<?php

	$this->headLink()->appendStylesheet($this->baseUrl() . '/modules/default/css/form.css');
	$title = new Snep_Title("Routing");
	$title->addOption('simulator', $this->baseUrl()."/index.php/default/simulator");
	echo $title->getHtml();
	
	
	$this->headLink()->appendStylesheet( $this->baseUrl() . "/modules/default/css/index.css" );
	$this->headScript()->appendFile( $this->baseUrl() .'/includes/javascript/scriptaculous/src/scriptaculous.js');
	echo $this->render('filter.phtml');

?>
<table>
   <thead>
      <tr>
         <th style="width: 5%;"> <?php echo Snep_Order::getLink($this, 'Code', 'id') ?> </th>
         <th style="width: 2%;"> <?php echo $this->translate('Active') ?> </th>
         <th> <?php echo Snep_Order::getLink($this, 'Source', 'origem') ?> </th>
         <th> <?php echo Snep_Order::getLink($this, 'Destiny', 'destino') ?> </th>
         <th> <?php echo Snep_Order::getLink($this, 'Description', 'desc') ?> </th>
         <th style="width: 5%;"> <?php echo Snep_Order::getLink($this, 'Priority', 'prio') ?> </th>
         <th colspan="3" class="action"> <?php echo $this->translate('Actions') ?>  </th>
      </tr>
   </thead>
   <tbody>
    <?php
    $c = false;
    foreach($this->routes as $route ):
        $c = !$c;
    ?>
        <tr class="c<?php echo $c ? 1 : 0; ?>">
            <td> <b> <?php echo $route['id'] ?> </b> </td>
            <td> <span style="cursor:pointer;" alt="<?php echo $this->translate("Enable/Disable"); ?>" id="id<?php echo $route['id']; ?>" class="regra<?php echo $route['ativa']; ?>" onclick="regras(<?php echo $route['id']; ?>)"></span> </td>
            <td> <?php echo $route['origem'] ?> </td>
            <td> <?php echo $route['destino'] ?> </td>
            <td> <?php echo $route['desc'] ?> </td>
            <td> <?php echo $route['prio'] ?> </td>

            <td class="action">
                <a class="alterar"  href='<?php echo $this->baseUrl(); ?>/index.php/route/frame/actionkey/edit-<?php echo $route['id'] ?>'></a>
            </td>
            <td class="action">
                <a class="duplicar"  href='<?php echo $this->baseUrl(); ?>/index.php/route/frame/actionkey/duplicate-<?php echo $route['id']?>' > </a>
            </td>
            <td class="action">
                <span class="excluir" onclick="remove_regra('<?php echo $route['id']; ?>');"> </span>
            </td>
        </tr>
    <?php endforeach ?>
</table>
<script type="text/javascript">

    function remove_regra(id) {
        var url = '<?php echo $this->baseUrl(); ?>/index.php/route/delete/' + id;

        if(confirm("Tem certeza de que deseja remover esta regra?")) {
            window.location.href= url;
        }
    }

    function regras(par) {
        if($('#id' + par).attr('class')=='regra0') {
            troca_status(par);
            $('#id' + par).attr('class', 'regra1');
        } else {
            troca_status(par);
            $('#id' + par).attr('class', 'regra0');
        }
    }

    function troca_status(id) {

        $.post('<?php echo $this->baseUrl(); ?>/index.php/route/toogle/', {route: id});
        
    }

</script>
<?php echo $this->render('pagination.phtml') ?>
