<?php
$title = new Snep_Title($this->translate("Entries"));
$title->addOption('multiadd', $this->baseUrl().'/index.php/extensions/multiadd/');
$title->addOption('import', $this->baseUrl()."/index.php/default/".Zend_Controller_Front::getInstance()->getRequest()->getControllerName() . '/import');
$title->addOption('export', $this->baseUrl()."/index.php/default/".Zend_Controller_Front::getInstance()->getRequest()->getControllerName() . '/export');
echo $title->getHtml();

$this->headLink()->appendStylesheet( $this->baseUrl() . "/modules/default/css/index.css" );
$this->headScript()->appendFile('/snep/includes/javascript/scriptaculous/src/scriptaculous.js');
$this->headScript()->appendFile('/snep/includes/javascript/registrations.js');
echo $this->render('filter.phtml');
?>
<?php if(!$this->all_writable): ?>
<div class="error_box">
    <p><?php echo $this->translate("Error: The following files are not writable by the system:"); ?></p>
    <ul>
        <?php
        foreach ($this->writable_files as $file => $status) {
            echo "<li>$file</li>";
        }
        ?>
    </ul>
</div>
<?php endif; ?>
<table>
   <thead>
      <tr>
         <th> <?php echo Snep_Order::getLink($this, 'Extension', 'name') ?></th>
         <th> <?php echo Snep_Order::getLink($this, $this->translate('Caller ID'), 'callerid') ?> </th>
         <th> <?php echo $this->translate('Channel') ?> </th>
         <th> <?php echo Snep_Order::getLink($this, 'Extension Group', 'group') ?> </th>
         <th colspan="3" class="action"> <?php echo $this->translate('Actions') ?>  </th>
      </tr>
   </thead>
   <tbody>
    <?php
    $c = 0;
    foreach($this->extensions as $cha => $val ): ?>
        <?php ($c ? $c = 0 : $c = 1 ); ?>
        <tr class="c<?php echo $c ?>">
            <td> <b> <?php echo $val['exten'] ?> </b> </td>
            <td> <?php echo $val['nome'] ?> </td>
            <td> <?php echo $val['channel'] ?> </td>
            <td><?php 
            $config = Zend_Registry::get('config');
            if ($config->system->language == "pt_BR"){
                if($val['group'] == "users"){
                    $val['group'] = "Usuarios";
            }
            }
            echo $val['group'];
            ?>
            
            <td class="action">
            	<?php if($val['exten'] != "admin" ||$this->user == "admin" ): ?>
                <a class="membros vinculos" href='<?php echo $this->url ?>/vinculos/id/<?php echo $val['exten'] ?>'></a>
                <?php endif; ?>
            </td>
            <td class="action">
            	<?php if($val['exten'] != "admin" ||$this->user == "admin" ): ?>
                <a class="alterar"  href='<?php echo $this->url ?>/edit/id/<?php echo $val['exten'] ?>'></a>
            	<?php endif; ?>
            </td>
            <td class="action">
            	<?php if($val['exten'] != "admin"): ?>
                <span class="excluir" onclick="remove_item('<?php echo $this->url ?>/delete/id/<?php echo $val['exten'] ?>', '<?php echo $this->translate('Are you sure you want to delete this extension?')?>' );"></span>
           		<?php endif; ?>
            </td>
            <?php /*?><td class="action">
                <a class="membros"  href='<?php echo $this->baseUrl(); ?>/index.php/permission/<?php echo $val['exten']?>' ></a>
            </td>
            */?>
        </tr>
    <?php endforeach ?>
</table>
<?php echo $this->render('pagination.phtml') ?>
