<?php
$title = new Snep_Title("Entries");
$title->addOption('add', $this->baseUrl() . '/index.php/extensions/add/');
echo $title->getHtml();
echo Snep_Bar::get($this->translate("add extension"), $this->translate("extensions"), $this->baseUrl() . "/index.php/default/extensions");
$this->headLink()->appendStylesheet($this->baseUrl() . '/modules/default/css/form.css');
?>

<div style="height:100%; margin: 5px 0 40px 0;" class="description_form"><p><h2>Ramais - Incluir Vários</h2>
    <p>Essa funcionalidade permite que sejam cadastrados mais de um ramal ao mesmo
        tempo no ToFalando. Para usar essa funcionalidade basta preencher corretamente o
        formulário selecionando qual será a interface dos novos ramais. Note que só é
        possível adicionar os ramais de um tipo de interface e grupos de cada vez.</p>
    <span style="display:none;" id="text_description">
        <ul>
            <li>
                <strong>Ramais:</strong> Range de ramais para inclusão, a notação desse
                campo segue o seguinte padrão: Ex: 1000-1050;1060;1063;1070-1100.
                Nesse caso será feito a adição de 50 ramais do 1000 até o 1050. Mais os
                ramais 1060 e 1063. Por fim mais 30 ramais do 1070 até o 1100.
            </li>
            <li>
                <strong>Grupo de Ramal:</strong> Grupo em que serão incluídos os novos
                ramais.
            </li>
            <li>
                <strong>Grupo de Captura:</strong> Grupo de captura para os ramais.
            </li>    
            <ul>
                <p> <li>
                    <strong>SIP e IAX2:</strong> Para ramais do tipo SIP ou IAX2 é
                    necessário preencher algumas informações sobre o protocolo:

                <li><strong>Atravessar NAT: </strong>Define se a conexão do Ramal irá ou
                    não através um NAT.</li>
                <li><strong>Controle de Qualidade: </strong>Define se haverá ou não controle
                    de qualidade nas ligações do Ramal.</li>
                <li><strong>Modo de DTMF: </strong>Define o modo de DTMF do Ramal (Dual-Tone
                    Multi-Frequency = Tons de multi frequências.</li>
                <li><strong>CODECS Permitidos: </strong>Define a sequencia de utilização dos codecs.</li></p>

                </li>
                <p><li><strong>Virtual: </strong>ramais com interfaces virtuais são mapeados em um tronco.
                    Ao selecionar um tronco para a interface virtual do ramal, a ligação para ele será feita discando através do tronco para o numero do ramal.</li></p>
                <li>
                    <p><strong>KHOMP: </strong> Para fazer a inclusão de vários ramais
                        em placas FXS da KHOMP basta que, com as placas já instaladas,
                        você selecione em quais placas os ramais serão distribuidos.
                        A distribuição ocorre de forma sequencial nos canais livres das
                        placas selecionadas.
                </li></p>
            </ul>
            </li>
        </ul>

        <strong>Obs:</strong> Por definição, a Senha será o número do ramal, repetido dua vezes. Exemplo: Numero Ramal=123,
        logo a Senha = 123123.</p>

    </span>
    <div style="position:absolute;display:none;margin:13px  0 0 -5px ; padding: 0px;;" class="less_description"><div>Mostrar menos informa&ccedil;&otilde;es</div> <div  style="float:right;position:absolute;relative;margin:-20px   0  0 170px;"  ><img    src="/snep/modules/default/img/less.png"> </div></div>

    <div  style="position:relative;clear:both;top:22px;margin:5px  0 0 0;"  class="more_description">Mostrar mais informa&ccedil;&otilde;es <img  style="position:absolute; margin:0  0 0  8px;"  src="/snep/modules/default/img/more.png"></div>

</div>

<?php if (!$this->all_writable): ?>
    <div class="error_box">
        <p><?php echo $this->translate("Error: The following files are not writable by the system:"); ?></p>
        <ul>
            <?php
            foreach ($this->writable_files as $file => $status) {
                echo "<li>$file</li>";
            }
            ?>
        </ul>
    </div>
<?php endif; ?>

<?php
if (isset($this->error)) {
    echo "<div class=\"error_box\" > {$this->error} </div>";
}
echo $this->form;
?>

<?php
$buttons = new Snep_Buttons();
$buttons->addOption('save', 'snep_form', true);
$buttons->addOption('cancel', $this->baseUrl() . '/index.php/extensions/');
echo $buttons->getHtml();
?>

<script type="text/javascript">

    subForm('technology-type', [null, null, "sip", "iax2", "virtual", "khomp", null]);

</script>

<script type="text/javascript">

    $(document).ready(function() {
        $(".more_description").click(function(e) {
            $('.description_form').animate({height: "100%", }, 500);
            $("#text_description").show();
            $(".less_description").show();
            $(".more_description").hide();
            e.preventDefault();
        });
        $(".less_description").click(function(e) {
            $(".description_form").animate({height: "100%", }, 500);
            $("#text_description").hide();
            $(".more_description").show();
            $(".less_description").hide();
            e.preventDefault();
        });
    })
</script>


