<?php
$this->headLink()->appendStylesheet( $this->baseUrl() . "/modules/default/css/form.css" );

$this->headLink()->appendStylesheet( $this->baseUrl() . "/modules/default/css/jqueryui.css" );
$this->headLink()->appendStylesheet( $this->baseUrl() . "/includes/multiselect/css/ui.multiselect.css" );

$this->headScript()->appendFile( $this->baseUrl() . '/includes/jquery-ui.min.js');
$this->headScript()->appendFile( $this->baseUrl() . '/includes/multiselect/js/plugins/localisation/jquery.localisation-min.js');
$this->headScript()->appendFile( $this->baseUrl() . '/includes/multiselect/js/plugins/scrollTo/jquery.scrollTo-min.js');
$this->headScript()->appendFile( $this->baseUrl() . '/includes/multiselect/js/ui.multiselect.js');

$this->headLink()->appendStylesheet($this->baseUrl() . '/modules/default/css/form.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/modules/default/css/form_config.css');
$title = new Snep_Title("Entries");
echo $title->getHtml();
echo Snep_Bar::get($this->translate("Entail"),  $this->translate("extensions"), $this->baseUrl()."/index.php/default/extensions");

echo $this->form;
?>

<div class="description_form"><p><h2>Vínculos:</h2>

<p>
Define uma lista de OUTROS Ramais sobre os
quais o Ramal em questão tem acesso às informações em relatórios. Se NENHUM vínculo for
definido, o Ramal em questão terá acesso completo aos relatórios de todos
os Ramais. isto é válido para quando o Ramal em questão efetuar LOGIN no ToFalando.
</p></p></div>

<?php 
$buttons = new Snep_Buttons();
$buttons->addOption('save', 'snep_form', true);
$buttons->addOption('cancel', $this->baseUrl().'/index.php/extensions/');
echo $buttons->getHtml();
?>

<style>
.ui-multiselect{
	border:solid 1px #DDD;
	border-radius:5px;
	padding: 2px;
	background-color: #FFF;
}
</style>
