<?php
$title = new Snep_Title("Entries");
$title->addOption('import', $this->baseUrl()."/index.php/default/".Zend_Controller_Front::getInstance()->getRequest()->getControllerName() . '/import');
$title->addOption('export', $this->baseUrl()."/index.php/default/".Zend_Controller_Front::getInstance()->getRequest()->getControllerName() . '/export');
echo $title->getHtml();
$this->headLink()->appendStylesheet( $this->baseUrl() . "/modules/default/css/index.css" );
$this->headScript()->prependFile('/snep/includes/javascript/scriptaculous/lib/prototype.js');
echo $this->render('filter.phtml');
?>

<table>
   <thead>
      <tr>
         <th class="action"> <?php echo Snep_Order::getLink($this, 'Code', 'name') ?> </th>
         <th> <?php echo Snep_Order::getLink($this, $this->translate('Name'), 'callerid') ?> </th>
         <th> <?php echo Snep_Order::getLink($this, $this->translate('Type'), 'type') ?> </th>
         <th> <?php echo Snep_Order::getLink($this, $this->translate('Interface Type'), 'trunktype') ?> </th>
         <th> <?php echo $this->translate('Time Credit (min:sec)') ?> </th>
         <th colspan="2" class="action"> <?php echo $this->translate('Actions') ?>  </th>
      </tr>
   </thead>
   <tbody>
       
    <?php
    $c = 0;
    foreach($this->trunks as $id => $trunk ): ?>

        <?php ($c ? $c = 0 : $c = 1 ); ?>
        <tr class="c<?php echo $c ?>">

            <td class="numeric"> <b> <?php echo $trunk['name'] ?> </b> </td>
            <td> <?php echo $trunk['callerid'] ?> </td>
            <td>
                <?php echo ( $trunk['trunktype'] == "T" ?  $this->translate("TDM") : $this->translate("IP") )  ?>
            </td>
            <td> <?php echo $trunk['type'] ?> </td>
            <td>
                <?php if ($trunk['saldo']) : ?>
                        <?php $date = new Zend_Date( $trunk['saldo'] ) ?>
                         <span style='color:#888'> 
                            <?php echo $date->toString('H:m:s') ?>
                         </span>
                    <?php else :  ?>
                        <?php echo $this->translate('Not configured') ?>
                <?php endif ?>
            </td>
            <td class="action">
                <a class="alterar" href="<?php echo $this->url ."/edit/trunk/".  $trunk['id'] ?>" ></a>
            </td>

            <td class="action">
                <a class="excluir" href="<?php echo $this->url ."/remove/id/".  $trunk['id'] . "/name/" . $trunk['name'] ?>"></a>
            </td>

        </tr>
    <?php endforeach ?>
</table>

<?php echo $this->render('pagination.phtml') ?>
