<?php
$this->headScript()->appendFile($this->baseUrl() . "/includes/javascript/snep.js", 'text/javascript');
$this->headLink()->appendStylesheet($this->baseUrl() . '/modules/default/css/form.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/modules/default/css/multiwx.css');

$title = new Snep_Title("Routing");
echo $title->getHtml();
echo Snep_Bar::get($this->subTitle,  "Expression Alias", $this->baseUrl()."/index.php/default/expression-alias");
?>

<div style="height:100%; margin: 5px 0 40px 0;" class="description_form"><p><h2>Alias de Expressão Regular</h2>

<p>
    Alias de expressão regular é usado para facilitar a criação de regras de
    negócio que partilhem de expressões regulares comuns.
</p>
<span style="display:none;" id="text_description">
<p>
    Para cadastrar um novo alias basta escolher um nome e determinar uma ou mais
    expressões regulares que serão usadas para comparar origens e destinos nas
    regras de negócio.
</p>

<p>
    Para que o alias seja válido basta que pelo menos uma das expressões
    casem com o parâmetro especificado na regra.
</p>
</p>
</span>
    <div style="position:absolute;display:none;margin:13px  0 0 -5px ; padding: 0px;;" class="less_description"><div>Mostrar menos informa&ccedil;&otilde;es</div> <div  style="float:right;position:absolute;relative;margin:-20px   0  0 170px;"  ><img    src="/snep/modules/default/img/less.png"> </div></div>

    <div  style="position:relative;clear:both;top:22px;margin:5px  0 0 0;"  class="more_description">Mostrar mais informa&ccedil;&otilde;es <img  style="position:absolute; margin:0  0 0  8px;"  src="/snep/modules/default/img/more.png"></div>

</div>

<?php echo $this->form; ?>


<?php
$buttons = new Snep_Buttons();
$buttons->addOption('save', 'snep_form', true);
$buttons->addOption('cancel', $this->baseUrl().'/index.php/expression-alias/');
echo $buttons->getHtml();
?>

<script type="text/javascript">
    
    var expr = new Array();

    window.onload = function() {
        exprObj = new MultiWx('expr', StringField);
        <?php echo $this->dataExprAlias; ?>
        exprObj.render();
    }

    function atualizaValues() {
        $('#exprValue').val(exprObj.getValue());
    }

    $('#snep_form').submit(atualizaValues);
</script>

<script type="text/javascript">

    $(document).ready(function() {
        $(".more_description").click(function(e) {
            $('.description_form').animate({height: "100%", }, 500);
            $("#text_description").show();
            $(".less_description").show();
            $(".more_description").hide();
            e.preventDefault();
        });
        $(".less_description").click(function(e) {
            $(".description_form").animate({height: "100%", }, 500);
            $("#text_description").hide();
            $(".more_description").show();
            $(".less_description").hide();
            e.preventDefault();
        });
    })
</script>